name: "Build"
permissions:
  contents: read

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  workflow_call:

jobs:
  build-native-linux:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:20.04
      options: --user root

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install compilation dependencies
        run: |
          apt-get update
          apt-get install -y \
            ca-certificates \
            cmake \
            curl \
            build-essential \
            gcc-aarch64-linux-gnu

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build with Gradle
        run: ./gradlew compileNative-aarch64-unknown-linux-gnu compileNative-x86_64-unknown-linux-gnu
        env:
          NATIVE_BUILD_MODE: "all"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v7
        with:
          name: linux-native-artifacts
          path: oniguruma-ffm/build/target

  build-native-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build with Gradle
        run: ./gradlew compileNative-x86_64-pc-windows-msvc compileNative-aarch64-pc-windows-msvc
        env:
          NATIVE_BUILD_MODE: "all"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v7
        with:
          name: windows-native-artifacts
          path: oniguruma-ffm/build/target

  build-native-mac:
    runs-on: macos-14

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build with Gradle
        run: ./gradlew compileNative-x86_64-apple-darwin compileNative-aarch64-apple-darwin
        env:
          NATIVE_BUILD_MODE: "all"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v7
        with:
          name: macos-native-artifacts
          path: oniguruma-ffm/build/target

  build:
    runs-on: ubuntu-22.04
    needs: [build-native-linux, build-native-windows, build-native-mac]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v8
        with:
          path: oniguruma-ffm/build/target
          merge-multiple: true

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build with Gradle
        run: ./gradlew build
        env:
          NATIVE_BUILD_MODE: "skip"
